### ISSUE TITLE
Remove humhub\widgets\ModalConfirm for Humhub 1.15

### ISSUE THREAD

**Issue by marc-farre** [humhub-contrib/linklist#61]
The module doesn't work on Humhub 1.15 because of `humhub\widgets\ModalConfirm` in https://github.com/humhub-contrib/linklist/blob/master/views/linklist/index.php

**Comment by yurabakhtin** [comment]
@luke- I confirm this module doesn't work with `v1.15`. I have detected this now while working on the https://github.com/humhub/humhub/issues/6486#issuecomment-1679002761.

I find the class `humhub\widgets\ModalConfirm` was removed here https://github.com/humhub/humhub/pull/6172/files#diff-4d0aaf58071b938d674a161ee566cd927eafb368a97f12adfbd4c4a918a49199. I guess @gevorgmansuryan deleted it because it is not easy to find where the class is used when not all modules are installed in system. Probably we should revert the deletion or try to find another solution for this module.

Also I find a place where the `use humhub\widgets\ModalConfirm;` still exists in core `v1.15` - https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/content/widgets/views/containerProfileImageMenu.php#L6

**Comment by luke-** [comment]
@yurabakhtin Thanks for the investigation.
@gevorgmansuryan  will take a look into this.
